### PR TITLE
Create visualino_fr-fr.ts

### PR DESCRIPTION
**Pull request by aishenri**
French translation

### CODE REVIEW

**Comment by vrruiz** [comment]
The file is empty :(

**Comment by aishenri** [comment]
yes I didn't cp the right one I am doing it now

**Comment by aishenri** [comment]
I don't remenber how to git push so I send it to you now

**Comment by aishenri** [comment]
I put file fr in dir ts but I am not sure the file fr in root has been deleted ?

**Comment by aishenri** [comment]
The french translation is finished and in github (Just time to update) how can I use my french translation in visualino I am using on ubuntu (file is in /usr/share/visualino/visualino_fr-fr.qm) ?

**Comment by aishenri** [comment]
Just in case there is a problem, I translated it again.

**Pull request closed without merging**
